config/routes.rb
Smalltalk::Application.routes.draw do
  root 'posts#index_all'

  # settings
  get '/settings', to: redirect('/settings/profile')
  get '/settings/profile', to: 'settings#profile', as: :profile_settings
  get '/settings/favourites', to: 'settings#favourites', as: :favourites_settings

  devise_scope :user do
    get '/settings/admin', to: 'devise/registrations#edit', as: :admin_settings
  end

  resources :sections, path_names: { edit: 'settings' } do
    resources :posts, except: [:index] do
      resources :comments, only: [:create] do
        post :vote_up
      end

      member do
        post :vote_up
      end
    end

    resources :collaborations, controller: 'collaborators', only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy, :update]
  end

  resources :shares, only: [:create, :new]

  # registrations controller defined so that sub-class is used
  devise_for :users, :controllers => { :registrations => :registrations }

  resources :users, only: [:show, :update]

  resources :search, only: [:index]
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy

  # collaborators associations
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user

  # favourites associations
  has_many :favourites
  has_many :favouriting_users, through: :favourites, source: :user

  # last section visit association
  has_many :last_section_visits

  validates :title, :user_id, presence: true
  validates :title, uniqueness: true

  after_create :add_owner_favourite

  def unread_post_count(user)
    @post_count = 0

    @last_user_visit = self.last_section_visits.find_by_user_id(user.id)

    if @last_user_visit
      @post_count = self.posts.where('created_at > ? and user_id != ?', @last_user_visit.last_visit_at, user.id).length
    end

    @post_count
  end

  def set_last_user_visit(user)
    @last_user_visit = self.last_section_visits.where(user_id: user.id).first_or_initialize
    @last_user_visit.last_visit_at = Time.now
    @last_user_visit.save
  end

  # overide find_by_title to be case insensitive
  def self.find_by_title(title)
    Section.where('lower(title) =?', title.downcase).first
  end

  # overide to_param to provide title instead of id
  def to_param
  	self.title.downcase
  end

  def is_user_favourite(user)
    self.favouriting_users.include?(user)
  end

  # checks if passed in user is owner
  def is_owner(user)
    self.user == user
  end

  # checks if passed in user is owner or collaborator
  def is_owner_or_collaborator(user)
    is_owner(user) || self.collaborators.include?(user)
  end

  def is_view_authorised(user)
    !private or (private and is_owner_or_collaborator(user))
  end

  # gets sections that user has authorisation to view
  def self.all_authorised(user)
    # public section or private section and user is owner or collaborator
    Section.find_by_sql(["SELECT sections.id, sections.title, sections.user_id, sections.created_at FROM sections
      LEFT JOIN collaborations ON collaborations.section_id = sections.id AND collaborations.user_id = ?
      WHERE sections.private = false OR (sections.private = true AND (sections.user_id = ? OR collaborations.id IS NOT NULL))", user.id, user.id])
  end

  private
    def add_owner_favourite
      self.favourites.build(section: self, user: self.user)

      self.save
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :set_favourite, only: [:show, :edit]
  before_action :authorise_user!, only: [:show, :edit, :update, :destroy]
  before_action :authorise_owner!, only: [:edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all_authorised(current_user).paginate(:page => params[:page])
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    # order by score and paginate results
    @posts = @section.posts.includes(:section, :user).order_by_score.paginate(:page => params[:page])

    @counter_reset = (params[:page].to_i > 1 ? params[:page].to_i * 10 : 0)

    # record user visit to section
    @section.set_last_user_visit(current_user)
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = current_user.sections.build(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to section_path(@section), notice: 'Section was successfully created.' }
        format.json { render action: 'show', status: :created, location: section_path(@section) }
      else
        format.html { render action: 'new' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to edit_section_path(@section), notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    def set_section
      @section = Section.find_by_title(params[:id])
    end

    # TODO: refactor into common code
    def set_favourite
      @favourite = @section.favourites.where(user_id: current_user.id).first
    end

    def section_params
      params.require(:section).permit(:user_id, :title, :description, :private)
    end

    # TODO: refactor into common code
    def authorise_user!
      if !@section.is_view_authorised(current_user)
        redirect_to root_path
      end
    end

    def authorise_owner!
      if !@section.is_owner(current_user)
        redirect_to section_path(@section)
      end
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_edit_section_form.html.erb
<%= form_for @section, html: { class: 'pure-form pure-form-stacked qt-form qt-form-full' } do |f| %>
  <div class="pure-g-r">
    <% if @section.errors.any? %>
      <div class="pure-u-1">
        <div id="error_explanation">
          <h2><%= pluralize(@section.errors.count, 'error') %> prohibited this section from being saved:</h2>

          <ul>
          <% @section.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="pure-u-1">
      <div class="pure-g-r">
        <div class="pure-u-1">
          <%= f.label :title %>
          <%= f.text_field :title, placeholder: 'Enter a title...', autocomplete: :off %>
        </div>
      </div>

      <div class="pure-g-r">
        <div class="pure-u-1">
          <%= f.label :decription %>
          <%= f.text_area :description, placeholder: 'Enter a description...', autocomplete: :off %>
        </div>
      </div>

      <div class="pure-g-r">
        <div class="pure-u-1 actions">
          <%= f.submit 'Update' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/sections/_new_section_form.html.erb
<%= form_for @section, html: { class: 'pure-form pure-form-stacked qt-form qt-form-full' } do |f| %>
  <div class="pure-g-r">
    <% if @section.errors.any? %>
      <div class="pure-u-1">
        <div id="error_explanation">
          <h2><%= pluralize(@section.errors.count, 'error') %> prohibited this section from being saved:</h2>

          <ul>
          <% @section.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="pure-u-1">
      <div class="pure-g-r">
        <div class="pure-u-1">
          <%= f.label :title %>
          <%= f.text_field :title, placeholder: 'Enter a title...', autofocus: true, autocomplete: :off %>
        </div>
      </div>

      <div class="pure-g-r">
        <div class="pure-u-1 bottom-separator bottom-separator-spacing">
          <%= f.label :description, 'Description' %>
          <%= f.text_area :description, placeholder: 'Enter a description...', autocomplete: :off %>
        </div>
      </div>

      <div class="pure-g-r">
        <div class="pure-u-1 availability bottom-separator bottom-separator-spacing">
          <div class="pure-g-r">
            <div class="pure-u-1">   
              <%= f.radio_button :private, 'false', checked: true %>
              <%= f.label :private, 'Public', value: 'false' %>
              <p>Anyone can see and contribute to this section.</p>
            </div>
          </div>
          <div class="pure-g-r">
            <div class="pure-u-1">
              <%= f.radio_button :private, 'true' %>
              <%= f.label :private, 'Private', value: 'true' %>
              <p class="no-bottom-margin">You choose who can see and contribute to this section.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="pure-g-r">
        <div class="pure-u-1 actions">
          <%= f.submit 'Create' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/sections/_section_menu.html.erb
<div class="pure-g-r content-menu">
  <div class="pure-u-1 content-menu-inner" style="position: relative;">
    <div id="share-link-interface" style="display: none;">
      <%= render 'shares/form' %>
    </div>

    <div class="pure-g">
      <div class="pure-u-1-2 section-heading">
        <h1 class="section-header">
          <%= link_to title, path %>
        </h1>

        <% if !@section.nil? %>
          <% if @favourite.nil? %>
            <%= form_for [@section, Favourite.new], html: { class: 'qt-form-favourite' } do |f| %>
              <%= f.button '', class: 'icon icon-ios7-star-outline' %>
            <% end %>
          <% else %>
            <%= form_for [@section, @favourite], html: { class: 'qt-form-favourite' }, method: :delete do |f| %>
              <%= f.button '', class: 'icon icon-ios7-star' %>
            <% end %>
          <% end %>

          <%= link_to '', new_share_path, class: 'icon icon-share share-link' %>
        <% end %>
      </div>

      <% if !@section.nil? %>
      <div class="pure-u-1-2 text-right">
        <nav>
          <ul>
            <li>
              <%= nav_link 'Posts', section_path(@section) %>
            </li>
            <% if @section.is_owner(current_user) %>
            <li>
              <%= nav_link 'Settings', edit_section_path(@section) %>
            </li>
            <% end %>
            <li>
              <%= nav_link 'Add Post', new_section_post_path(@section), class: 'section-add-post-link' %>
            </li>
          </ul>
        </nav>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sections/_sections_menu.html.erb
<div class="pure-g-r content-menu">
  <div class="pure-u-1 content-menu-inner">
    <div class="pure-g">
      <div class="pure-u-1-2 section-heading">
        <h1 class="section-header">
          <%= link_to 'Sections', sections_path %>
        </h1>
      </div>

      <div class="pure-u-1-2 text-right">
        <nav>
          <ul>
            <li>
              <%= nav_link 'Add Section', new_section_path, class: 'section-add-post-link' %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/sections/edit.html.erb
<div class="edit">
  <%= render partial: 'section_menu', locals: { title: @section.title, path: section_path(@section) } %>

  <div class="pure-g-r content-container">
    <div class="pure-u-1 content">
      <div class="inner-container">
        <header>
          <h2>Settings</h2>
        </header>

        <%= render 'edit_section_form' %>
      </div>
    </div>
  </div>

  <div class="pure-g-r content-container collaborators">
    <div class="pure-u-1 content">
      <div class="inner-container">
        <header>
          <h2>Collaborators</h2>
        </header>

        <% @section.collaborations.each do |c| %>
          <div class="pure-g-r bottom-separator">
            <div class="pure-u-2-3 details">
              <%= c.user.full_name %>
            </div>

            <div class="pure-u-1-3 actions">
              <%= form_for [@section, c], html: { class: 'pure-form pure-form-stacked qt-form qt-form-full' }, method: :delete do |f| %>
                <%= f.submit '&times;'.html_safe %>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="pure-g-r">
          <div class="pure-u-1">
            <%= form_for [@section, Collaboration.new], html: { class: 'pure-form pure-form-stacked qt-form qt-form-full' } do |f| %>
              <div class="pure-g-r">
                <div class="pure-u-1">
                  <%= f.label :user_id, 'Collaborator Name' %>
                  <%= f.text_field :user_id, placeholder: 'Enter a collaborator\'s name...', autocomplete: :off %>

                  <%= f.hidden_field :section_id, value: @section.id %>
                </div>

                <div class="pure-u-1 actions">
                  <%= f.submit 'Add' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="pure-g-r content-container">
    <div class="pure-u-1 content">
      <div class="inner-container">
        <header>
          <h2>Actions</h2>
        </header>

        <div class="pure-g-r <%= 'bottom-separator bottom-separator-spacing' if @section.is_owner(current_user) %>">
          <div class="pure-u-1">
            <%= form_for @section, html: { class: 'pure-form pure-form-stacked qt-form qt-form-full' } do |f| %>
              <div class="pure-g-r">
                <div class="pure-u-1">
                  <legend>
                    <%= 'Make this section ' + (@section.private? ? 'public' : 'private') %>
                  </legend>
                </div>

                <div class="pure-u-2-3">
                  <p class="action-description no-bottom-margin">
                    <% if @section.private %>
                      Make this section visible to everyone.
                    <% else %>
                      Hide this section from everyone but the owner and collaborators.
                    <% end %>
                  </p>
                </div>

                <%= f.hidden_field :private, value: !@section.private %>

                <div class="pure-u-1-3 actions">
                  <%= f.submit 'Make ' + (@section.private? ? 'public' : 'private'), class: 'danger' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="pure-g-r bottom-separator bottom-separator-spacing section-ownership">
          <div class="pure-u-1">
            <%= form_for @section, html: { class: 'pure-form pure-form-stacked qt-form qt-form-full' } do |f| %>
              <div class="pure-g-r">
                <div class="pure-u-1 legend-container">
                  <legend>
                    Change section owner
                  </legend>
                </div>

                <div class="pure-u-1">
                  <%= f.label :user_id, 'Owner Name' %>
                  <%= f.text_field :user_id, placeholder: 'Enter the new owner\'s name...', autocomplete: :off %>

                  <%= f.hidden_field :section_id, value: @section.id %>
                </div>

                <div class="pure-u-1 actions">
                  <%= f.submit 'Change owner', class: 'danger' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="pure-g-r">
          <div class="pure-u-1">
            <%= form_for @section, html: { class: 'pure-form pure-form-stacked qt-form qt-form-full' }, method: :delete do |f| %>
              <div class="pure-g-r">
                <div class="pure-u-1">
                  <legend>
                    Delete this section
                  </legend>
                </div>

                <div class="pure-u-2-3">
                  <p class="action-description no-bottom-margin">Deleting a section is permanent and cannot be undone.</p>
                </div>

                <div class="pure-u-1-3 actions">
                  <%= f.submit 'Delete section', class: 'danger' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sections/index.html.erb
<div class="index">
  <%= render 'sections_menu' %>

  <div class="pure-g-r">
    <div class="pure-u-1 content">
      <div class="pure-g-r">
        <% @sections.each do |section| %>
          <div class="pure-u-1-2 item">
            <div class="inner-container">
              <h1>
                <%= link_to section.title, section_path(section) %>
              </h1>

              <div class="details">
                <%= section.posts.count %> <%= pluralizer section.posts.count, 'post' %> since created <%= time_ago_in_words(section.created_at) %> ago · owned by <%= link_to section.user.full_name, user_path(section.user) %>
              </div>
            </div>
          </div>
        <% end %>

        <%= will_paginate @posts, :page_links => false, :previous_label => 'Previous', :next_label => 'Next' %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>

app/views/sections/new.html.erb
<div class="new">
  <%= render 'sections_menu' %>

  <div class="pure-g-r">
    <div class="pure-u-1 content">
      <div class="inner-container">
        <%= render 'new_section_form' %>
      </div>
    </div>
  </div>
</div>

app/views/sections/show.html.erb
<div class="show">
  <%= render partial: 'sections/section_menu',  locals: { title: @section.title, path: section_path(@section) } %>
  
  <%= render partial: 'posts/post_list', locals: { posts: @posts, counter_reset: @counter_reset, show_details: false } %>
</div>