config/routes.rb
Smalltalk::Application.routes.draw do
  root 'posts#index_all'

  # settings
  get '/settings', to: redirect('/settings/profile')
  get '/settings/profile', to: 'settings#profile', as: :profile_settings
  get '/settings/favourites', to: 'settings#favourites', as: :favourites_settings

  devise_scope :user do
    get '/settings/admin', to: 'devise/registrations#edit', as: :admin_settings
  end

  resources :sections, path_names: { edit: 'settings' } do
    resources :posts, except: [:index] do
      resources :comments, only: [:create] do
        post :vote_up
      end

      member do
        post :vote_up
      end
    end

    resources :collaborations, controller: 'collaborators', only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy, :update]
  end

  resources :shares, only: [:create, :new]

  # registrations controller defined so that sub-class is used
  devise_for :users, :controllers => { :registrations => :registrations }

  resources :users, only: [:show, :update]

  resources :search, only: [:index]
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  # GET /settings/profile
  # GET /settings/profile.json
  def profile
  end

  # GET /settings/favourites
  # GET /settings/favourites.json
  def favourites
    @favourites = current_user.favourites
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_settings_menu.html.erb
<div class="pure-g-r content-menu">
  <div class="pure-u-1 content-menu-inner">
    <div class="pure-g-r">
      <div class="pure-u-1-2 section-heading">
        <h1 class="section-header">
          <%= link_to current_user.full_name, user_path(current_user) %>
        </h1>
      </div>

      <div class="pure-u-1-2 text-right">
        <nav>
          <ul>
            <li>
              <%= nav_link 'Profile', profile_settings_path %>
            </li>
            <li>
              <%=  nav_link 'Favourites', favourites_settings_path %>
            </li>
            <li>
              <%= nav_link 'Admin', admin_settings_path %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/settings/favourites.html.erb
<div class="favourites">
  <%= render 'settings_menu' %>

  <div class="pure-g-r item-list">
    <div class="pure-u-1 content">
      <ul>
        <% @favourites.each do |favourite| %>
          <li>
            <div class="pure-g">
              <div class="favourite-controls">
                <%= form_for [favourite.section, favourite], html: { class: 'qt-form-favourite' }, method: :delete do |f| %>
                  <%= f.button '', class: 'icon icon-ios7-star' %>
                <% end %>
              </div>

              <div class="pure-u-1">
                <header>
                  <%= link_to favourite.section.title, section_path(favourite.section) %>
                </header>
                <div class="details">
                  added <%= time_ago_in_words(favourite.created_at) %> ago
                </div>
              </div>

              <div class="position-controls">
                <%= form_for [favourite.section, favourite], html: { class: 'pure-form pure-form-stacked qt-form qt-form-favourite-move-up' } do |f| %>
                  <div class="pure-g">
                    <div class="pure-u-1 actions">
                      <%= f.hidden_field :direction, value: 'up' %>

                      <%= f.button '', class: 'icon icon-arrow-up-b' %>
                    </div>
                  </div>
                <% end %>

                <%= form_for [favourite.section, favourite], html: { class: 'pure-form pure-form-stacked qt-form qt-form-favourite-move-down' } do |f| %>
                  <div class="pure-g">
                    <div class="pure-u-1 actions">
                      <%= f.hidden_field :direction, value: 'down' %>

                      <%= f.button '', class: 'icon icon-arrow-down-b' %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/settings/profile.html.erb
<div class="profile">
  <%= render 'settings_menu' %>

  <div class="pure-g-r">
    <div class="pure-u-1 content">
      <div class="inner-container">
        <%= render 'users/form', user: current_user %>
      </div>
    </div>
  </div>
</div>