config/routes.rb
Smalltalk::Application.routes.draw do
  root 'posts#index_all'

  # settings
  get '/settings', to: redirect('/settings/profile')
  get '/settings/profile', to: 'settings#profile', as: :profile_settings
  get '/settings/favourites', to: 'settings#favourites', as: :favourites_settings

  devise_scope :user do
    get '/settings/admin', to: 'devise/registrations#edit', as: :admin_settings
  end

  resources :sections, path_names: { edit: 'settings' } do
    resources :posts, except: [:index] do
      resources :comments, only: [:create] do
        post :vote_up
      end

      member do
        post :vote_up
      end
    end

    resources :collaborations, controller: 'collaborators', only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy, :update]
  end

  resources :shares, only: [:create, :new]

  # registrations controller defined so that sub-class is used
  devise_for :users, :controllers => { :registrations => :registrations }

  resources :users, only: [:show, :update]

  resources :search, only: [:index]
end

app/models/post.rb
class Post < Voteable
  belongs_to :user
  belongs_to :section

  has_many :comments, dependent: :destroy

  validates :title, :user_id, :section_id, presence: true
  validate :link_url_or_content_must_be_set

  self.per_page = 20

  def short_link_url
    URI.parse(self.link_url).host
  end

  # checks if passed in user is post owner or section owner/collaborator
  def is_action_authorised(user)
    self.user == user || section.is_owner(user)
  end

  private

    def link_url_or_content_must_be_set
      if link_url.blank? and content.blank?
        errors[:base] << 'One or both of the link_url and content fields must be set'
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_section, except: [:index_all]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote_up, :vote_down]
  before_action :set_favourite, only: [:index, :show, :new, :edit, :update]
  before_action :authorise_user!, except: [:index_all]
  before_action :authorise_owner!, only: [:edit, :update, :destroy]
  
  # must occur after section and post have been set
  include VoteableConcern

  # GET /posts
  # GET /posts.json
  def index_all
    # order by score and paginate results
    @posts = Post.includes(:section, :user).order_by_score.paginate(:page => params[:page])

    @counter_reset = (params[:page].to_i > 1 ? params[:page].to_i * 10 : 0)
  end

  # GET /posts
  # GET /posts.json
  def index
    # order by score and paginate results
    @posts = @section.posts.order_by_score.paginate(:page => params[:page])

    @counter_reset = (params[:page].to_i > 1 ? params[:page].to_i * 10 : 0)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new

    @post_comments = @post.comments.order_by_score
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @section.posts.build(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to section_post_path(@section, @post), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: section_post_path(@section, @post) }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to section_post_path(@section, @post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to section_path(@section) }
      format.json { head :no_content }
    end
  end

  # POST /posts/1/vote_up
  def vote_up
    current_user.vote_for(@post)

    redirect_to section_post_path(@section, @post), notice: 'Your vote has been successfully added.'
  end

  private
    def set_section
      @section = Section.find_by_title(params[:section_id])
    end

    def set_post
      @post = Post.find(params[:id])
    end

    # TODO: refactor into common code
    def set_favourite
      @favourite = @section.favourites.where(user_id: current_user.id).first
    end

    # TODO: refactor into common code
    def authorise_user!
      if !@section.is_view_authorised(current_user)
        redirect_to root_path
      end
    end

    def authorise_owner!
      if !@post.is_action_authorised(current_user)
        redirect_to section_post_path(@section, @post), notice: 'You do not have permission to update this post.'
      end
    end

    def validate_voted_on!
      if @post.user == current_user
        redirect_to section_post_path(@section, @post), notice: 'You can\'t vote on your own post.'
      elsif current_user.voted_on?(@post)
        redirect_to section_post_path(@section, @post), notice: 'You have already voted on this post.'
      end
    end

    def update_scores
      Delayed::Job.enqueue VoteablePostsJob.new()
    end

    def post_params
      params.require(:post).permit(:title, :link_url, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_for [@section, @post, @comment], html: { class: 'pure-form pure-form-stacked qt-form qt-form-full' } do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, 'error') %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, :placeholder => 'Write a comment...', autofocus: true, autocomplete: :off %>
  </div>
  <div class="actions">
    <%= f.submit 'Add Comment' %>
  </div>
<% end %>

app/views/posts/_post_form.html.erb
<%= form_for [@section, @post], html: { class: 'pure-form pure-form-stacked qt-form qt-form-split' } do |f| %>
  <div class="pure-g-r">
    <% if @post.errors.any? %>
      <div class="pure-u-1">
        <div id="error_explanation" class="pure-u-1">
          <h2><%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:</h2>

          <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="pure-u-1-2 left-field">
      <%= f.label :title %>
      <%= f.text_field :title, :placeholder => 'Enter a title...', :autofocus => true, autocomplete: :off %>
    </div>

    <div class="pure-u-1-2 right-field">
      <%= f.label :link_url, 'Link', style: 'width: 100%;' %>
      <%= f.text_field :link_url, :placeholder => 'Enter a link...', autocomplete: :off %>
    </div>
    
    <div class="pure-u-1 field">
      <%= f.label :content %>
      <%= f.text_area :content, :placeholder => 'Write a post...', autocomplete: :off %>
    </div>
    
    <div class="pure-u-1 actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/posts/_post_list.html.erb
<div class="pure-g-r item-list post-list">
  <div class="pure-u-1 content">
    <ol style="counter-reset: li <%= counter_reset %>">
      <% posts.each do |post| %>
        <li>
          <header>
            <% if post.link_url.blank? %>
              <%= link_to post.title, section_post_path(post.section, post) %>
            <% else %>
              <%= link_to post.title, post.link_url, target: '_blank' %>
            <% end %>
          </header>
          <div class="details">
            <%= vote_pluralizer post %> by <%= link_to post.user.full_name, user_path(post.user) %>

            <% if show_details %>
              in <%= link_to post.section.title, section_path(post.section) %>
            <% end %>

             <%= time_ago_in_words(post.created_at) %> ago 
          
             · <%= link_to post.comments.count.to_s + ' ' + pluralizer(post.comments.count, 'comment'), section_post_path(post.section, post) %>

            <% if !post.link_url.blank? %>
               · <%= post.short_link_url %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ol>

    <%= will_paginate @posts, :page_links => false, :previous_label => 'Previous', :next_label => 'Next' %>
    <div class="clearfix"></div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="edit">
  <%= render partial: 'sections/section_menu', locals: { title: @section.title, path: section_path(@section) } %>

  <div class="pure-g-r">
    <div class="pure-u-1 content">
      <div class="inner-container">
        <%= render 'post_form' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index_all.html.erb
<div class="index_all">
  <%= render partial: 'sections/section_menu', locals: { title: 'Front Page', path: root_path } %>

  <%= render partial: 'posts/post_list', locals: { posts: @posts, counter_reset: @counter_reset, show_details: true } %>
</div>

app/views/posts/new.html.erb
<div class="new">
  <%= render partial: 'sections/section_menu', locals: { title: @section.title, path: section_path(@section) } %>

  <div class="pure-g-r">
    <div class="pure-u-1 content">
      <div class="inner-container">
        <%= render 'post_form' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="show">
  <%= render partial: 'sections/section_menu', locals: { title: @section.title, path: section_path(@section) } %>

  <div class="pure-g-r">
    <div class="pure-u-1 content">
      <div class="first-post">
        <header>
          <div class="vote-controls">
            <%= vote_up_button vote_up_section_post_path(@section, @post) %>
          </div>
          <div class="header-content">
        	  <h1>
              <% if @post.link_url.blank? %>
                <%= @post.title %>
              <% else %>
                <%= link_to @post.title, @post.link_url, target: '_blank' %>
              <% end %>
            </h1>
            <div class="details">
              <%= vote_pluralizer @post %> by <%= link_to @post.user.full_name, user_path(@post.user) %> <%= time_ago_in_words(@post.created_at) %> ago

              <% if !@post.link_url.blank? %>
                 · <%= @post.short_link_url %>
              <% end %>

              <% if @post.is_action_authorised(current_user) %>
                 · <%= link_to 'Edit', edit_section_post_path(@section, @post) %> · 

                <%= form_for [@section, @post], html: { class: 'qt-form-link' }, method: :delete do |f| %>
                  <% f.submit 'Delete', class: 'danger' %>
                <% end %>
              <% end %>
            </div>
          </div>
        </header>

        <% if !@post.content.blank? %>
          <div class="inner-content">
            <%= simple_format(@post.content) %>
          </div>
        <% end %>
      </div>

      <div class="new-comment">
        <%= render 'comment_form' %>
      </div>

      <div class="comments">
      	<ol>
          <% @post_comments.each do |comment| %>
            <li>
              <div class="pure-g-r">
                <div class="pure-u-1-5">
                  <div class="side-container">
                    <div class="vote-controls">
                      <%= vote_up_button section_post_comment_vote_up_path(@section, @post, comment) %>
                    </div>
                    <div class="details">
                    	<div class="inner-details">
                        <%= link_to comment.user.full_name, user_path(comment.user) %>
                      </div>
                      <div class="inner-details">
                        <%= vote_pluralizer comment %>
                      </div>
                      <div class="inner-details">
                        <%= time_ago_in_words(comment.created_at) %> ago
                      </div>
                    </div>
                  </div>
                </div>
                <div class="pure-u-4-5">
                  <div class="inner-content">
                    <%= simple_format(comment.content) %>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>