config/routes.rb
Smalltalk::Application.routes.draw do
  root 'posts#index_all'

  # settings
  get '/settings', to: redirect('/settings/profile')
  get '/settings/profile', to: 'settings#profile', as: :profile_settings
  get '/settings/favourites', to: 'settings#favourites', as: :favourites_settings

  devise_scope :user do
    get '/settings/admin', to: 'devise/registrations#edit', as: :admin_settings
  end

  resources :sections, path_names: { edit: 'settings' } do
    resources :posts, except: [:index] do
      resources :comments, only: [:create] do
        post :vote_up
      end

      member do
        post :vote_up
      end
    end

    resources :collaborations, controller: 'collaborators', only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy, :update]
  end

  resources :shares, only: [:create, :new]

  # registrations controller defined so that sub-class is used
  devise_for :users, :controllers => { :registrations => :registrations }

  resources :users, only: [:show, :update]

  resources :search, only: [:index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quicktalk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1">
</head>
<body>
  <div id="layout" class="pure-g-r <%= user_signed_in? ? 'open' : '' %>">
    <a href="#menu" id="menuLink" class="pure-menu-link">
      <span></span>
    </a>

    <div id="mobileHeader" class="pure-u-1">
      <h1>Quicktalk</h1>
    </div>

    <% if user_signed_in? %>
    <div id="menu" class="pure-u">
      <div class="menu-logo">
        <%= link_to 'Quicktalk', root_path %>
      </div>

      <div class="menu-search">
        <%= form_for '', html: { class: 'pure-form pure-form-stacked qt-form qt-form-main-search' } do |f| %>
          <%= f.text_field :private, placeholder: 'Search...' %>

          <%= f.button '', class: 'icon icon-search' %>
        <% end %>
      </div>

      <nav>
        <header>
          Browse
        </header>
        <ul>
          <li>
            <%= nav_link 'Front Page', root_path %>
          </li>
          <li>
            <%= nav_link 'Sections', sections_path %>
          </li>
        </ul>
      </nav>

      <% if @menu_favourites.length > 0 %>
      <nav>
        <header>
          Favourites

          <%= link_to '', favourites_settings_path, class: 'icon icon-ios7-gear' %>
        </header>
        <ul>
          <% @menu_favourites.each do |favourite| %>
            <% @unread_post_count = favourite.section.unread_post_count(current_user) %>

            <li>
              <%= nav_link section_path(favourite.section) do %>
                <%= favourite.section.title %>

                <% if @unread_post_count > 0 %>
                  <span>
                    <%= @unread_post_count %>
                  </span>
                <% end %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
      <% end %>

      <div class="menu-bottom">
        <div class="pure-g">
          <div class="pure-u-1-2">
            <%= link_to '', user_path(current_user), class: 'icon icon-person' %>
          </div>

          <div class="pure-u-1-2">
            <%= link_to '', settings_path, class: 'icon icon-ios7-gear' %>
          </div>
<!-- 
          <div class="pure-u-1-3">
            <%= button_to '', destroy_user_session_path, method: :delete, class: 'menu-logout-button icon icon-log-out', form_class: 'qt-form-signout' %>
          </div> -->
        </div>
      </div>
    </div>
    <% end %>

    <div id="container" class="pure-u-1">
      <div id="main" class="pure-g-r <%= controller.controller_name %>">
        <div class="pure-u-1">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    var menu = document.getElementById('menu'),
        menuLink = document.getElementById('menuLink'),
        layout = document.getElementById('layout'),
        mobileHeader = document.getElementById('mobileHeader');

    toggleClass = function (element, className) {
      var classes = element.className.split(/\s+/),
      length = classes.length,
      i = 0;

      for(; i < length; i++) {
        if (classes[i] === className) {
          classes.splice(i, 1);
          break;
        }
      }
      // The className is not found
      if (length === classes.length) {
        classes.push(className);
      }

      element.className = classes.join(' ');
    };

    menuLink.onclick = function (e) {
      e.preventDefault();

      var active = 'active';

      toggleClass(layout, active);
      toggleClass(menu, active);
      toggleClass(menuLink, active);
      toggleClass(mobileHeader, active);
    };
  </script>
</body>
</html>